### ISSUE TITLE
The library uses 2 timers

### ISSUE THREAD

**Issue by jantje** [PaulStoffregen/Tlc5940#1]
Hi Paul
I have used this library and I found out it uses 2 timers on arduino and on you teensy (timer 1 and timer 2).
This is very unfortunately for me as I also want to drive servos (4 to be precise) with the servo library which uses timer 1.
I'm considering cloning and modifying the library so it only uses one timer. 

However I read somewhere the statement of the author it can not be done with one timer.

I just can't get my head around why one would need 2 timers in the same library. 
As I'm not skilled in timers and all these low level functionality, I would like to know your opinion/advise on this before I dive into coding/learning.
Best regards
Jantje

**Comment by rlogiacco** [comment]
Sorry to revive this after more than 6 months, but I'm having a similar issue to the one @jantje had with this library: I need, on an Arduino Pro Mini a timer with an 800Hz frequency to update my 8x8x8 LED cube at a global 100Hz.

I had a look at the TL5940 datasheet and, for what I understand from the timing diagram, XLAT goes high for 20ns after each data block is sent over (after the LSB has been transmitted) and BLANK goes low right after XLAT or at every GSCLK turnaround (4096 cycles).

If that's correct, can't we just use the GSCLK timer to fire this two events? To me it seems both interrupts are somehow driven by the GSCLK timer:

```
    // Timer 1 setup
    TCCR1A = _BV(COM1B1);  // non inverting, output on OC1B, BLANK
    TCCR1B = _BV(WGM13);   // Phase/freq correct PWM, ICR1 top
    OCR1A = 1;             // duty factor on OC1A, XLAT is inside BLANK
    OCR1B = 2;             // duty factor on BLANK (larger than OCR1A (XLAT))
    ICR1 = TLC_PWM_PERIOD; // see tlc_config.h

   // Timer 2 setup
    TCCR2A = _BV(COM2B1)      // set on BOTTOM, clear on OCR2A (non-inverting),
                              // output on OC2B
           | _BV(WGM21)       // Fast pwm with OCR2A top
           | _BV(WGM20);      // Fast pwm with OCR2A top
    TCCR2B = _BV(WGM22);      // Fast pwm with OCR2A top
    OCR2B = 0;                // duty factor (as short a pulse as possible)
    OCR2A = TLC_GSCLK_PERIOD; // see tlc_config.h
    TCCR2B |= _BV(CS20);      // no prescale, (start pwm output)
    TCCR1B |= _BV(CS10);      // no prescale, (start pwm output)
```

Even in the configuration file it is reported `TLC_PWM_PERIOD` is `( (TLC_GSCLK_PERIOD - 1) * 4096)`: to me it seems it should be possible to pulse the XLAT and BLANK pins by watching the number of times the GSCLK timer has fired: this might obviously reduce the GSCLK frequency a bit as rather than having it generated as an interrupt PWM it should be pulsed within an ISR.
Would you believe that can do? 

The only other alternatives I can see are either to drop `millis()` and use Timer0 or to have the GSCLK being generated by an external square wave IC and just controlling that IC from the Arduino...

**Comment by jantje** [comment]
@rlogiacco 
I think Paul is extremely talented in this area and trustworthy. If he states:
>"I'm pretty familiar with the timers and **I do not see any viable way**. That doesn't necessarily mean it's "impossible", only that **it's beyond any solution I can see.**"

I think that; even if I could find/implement a solution -Paul can not see-, I can't spend the time to find/implement that solution.
So I searched a different path and I advice you to do the same.

Best regards
Jantje

**Comment by PaulStoffregen** [comment]
There are newer chips from TI with less clocking requirements.

There are other Arduino compatible board with far more timer resources (Teensy 3.1 of course would be the one I recommend....)

Or you could build an external clock circuit to relieve the need for the Arduino to generate GSCLK.

Those are all viable paths forward.  A path that will not move forward would involve waiting for me to do more work on this older Arduino library.  I will likely port it to other chips, but I'm not planning to ever change its design.

**Comment by rlogiacco** [comment]
Well, I would happily switch to another IC if I hadn't bought already 10 of these: I believe it will cheaper to source 2 external square wave generators than buy 8 more drivers (I'm building 2 of these).
I will give the timer0 path a try before ordering the clock generators: I think I could drop the delay() and millis() functions in place of an equivalent custom elapsed() function, using timer 0 both to tick the clock and switch layer.
Currently millis has approx 1kHz frequency and I may step down my cube update frequency to 500Hz, once every 2 ticks...

I understand your reluctance to update an old library for an old chip and I appreciate your quick answer: thanks!
